catalogueUrl: "http://privado.ai/catalogue"
tagsUrl: "http://catalogue.privado.ai/tags"
cartsUrl: "http://privado.ai/carts/carts"
ordersUrl: "http://privado.ai/orders"
customersUrl: "http://privado.ai/user/customers"
addressUrl: "http://privado.ai/user/addresses"
cardsUrl: "http://privado.ai/user/cards"
loginUrl: "http://privado.ai/user/login"
registerUrl: "http://privado.ai/user/register"
registerUrlPath: "/users/register"
